module madgwick_filter_rtc
{
  interface MadgwickFilterService
  {
    /**
     * @struct MadgwickFilterParam
     * @brief MadgwickFilter Parameters. See http://wiki.ros.org/imu_filter_madgwick
     */
    struct MadgwickFilterParam
    {
      double gain;
      double zeta;
    };

    void setParams(in MadgwickFilterParam i_param);

    void getParams(out MadgwickFilterParam i_param);

  };
};
